name: chatmate
description: "A sleek, dark-themed AI chatbot app that brings your conversations to life with a modern design and intuitive chat interface."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  emoji_picker_flutter: ^4.0.0
  speech_to_text: ^7.0.0
  file_picker: '>=8.1.2'
  url_launcher: ^6.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  http: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
      - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
